### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by JrantKing** [MJRLegends/ExtraPlanets#1]
---- Minecraft Crash Report ----
// There are four lights!

Time: 16-2-6 14:46
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.mjr.extraplanets.planets.ExtraPlanets_Planets.initializePlanets(ExtraPlanets_Planets.java:177)
	at com.mjr.extraplanets.planets.ExtraPlanets_Planets.init(ExtraPlanets_Planets.java:62)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mjr.extraplanets.planets.ExtraPlanets_Planets.initializePlanets(ExtraPlanets_Planets.java:177)
	at com.mjr.extraplanets.planets.ExtraPlanets_Planets.init(ExtraPlanets_Planets.java:62)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 75901896 bytes (72 MB) / 346923008 bytes (330 MB) up to 2112618496 bytes (2014 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.5.18
	LaunchWrapper: 43 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: lain.mods.inputfix.InputFixTransformer
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: myrathi.infinibows.asm.BowTransformer
          - Transformer: stevekung.mods.moreplanets.plugin.asm.MorePlanetsTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: CustomSteve.ASM.ClassTransformer
          - Transformer: cn.lambdalib.core.asm.RegistryTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: stevekung.mods.moreplanets.plugin.asm.MorePlanetsAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: com.gildedgames.util.threadedlighting.asm.TLTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: fastcraft.G
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHI	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	customsteve{1.1.0-Beta} [CustomSteve] (CustomSteve1710-Beta.jar) 
	UCHI	LambdaLib|Core{1.1.1} [LambdaLib|Core] (minecraft.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHI	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHI	FastCraft{1.22} [FastCraft] (fastcraft-1.22-ctest17.jar) 
	UCHI	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHI	DamageIndicatorsMod{3.2.3} [Damage Indicators] (1.7.10DamageIndicatorsMod-3.2.3.jar) 
	UCHI	MemoryCleaner{1.0} [Memory Cleaner] ([内存清理MOD][1.7.10].jar) 
	UCHI	DynamicLights{1.3.8} [Dynamic Lights] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCHI	Waila{1.5.10} [Waila] ([方块显示MOD][1.7.10].jar) 
	UCHI	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.440.jar) 
	UCHI	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.440.jar) 
	UCHI	GalaxySpace{1.0.6} [GalaxySpace] ([星系附属00]GalaxySpace-1.0.6+STABLE.jar) 
	UCHE	ExtraPlanets{1.0-3.2} [ExtraPlanets] ([星系附属01]ExtraPlanets-1.0-Pre 3.2.jar) 
	UCHI	MorePlanet{1.3.0} [More Planets] ([星系附属02]More-Planets-1.3.0-1.7.10.jar) 
	UCHI	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([物品整理]InventoryTweaks-1.59-dev-152.jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHI	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([耐久显示]ArmorStatusHUD.jar) 
	UCHI	LambdaLib{1.1.1} [LambdaLib] (LambdaLib-1.1.1.jar) 
	UCHI	academy-craft{1.0pr3_1} [Academy Craft] (AcademyCraft-1.0pr3_1.jar) 
	UCHI	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHI	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge[hukk汉化].jar) 
	UCHI	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHI	Obsidiancraft{2.0.0} [Obsidiancraft] (obsidianCraft.jar) 
	UCHI	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHI	UnicodeFontFixer{1.1.9-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.9-mc1.7.10.jar) 
	UCHI	WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.5.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by MJRLegends** [comment]
What version of forge and galacticraft are you using

**Comment by JrantKing** [comment]
forge 1614
Galacticraft-1.7 - 440

**Comment by MJRLegends** [comment]
Try removing all other galacticcraft addon and then try

**Comment by MJRLegends** [comment]
Guessing you fixed it?

**Comment by JrantKing** [comment]
yeah,it works

2016-02-07 22:30 GMT+08:00 MJRLegends <notifications@github.com>:
