### ISSUE TITLE
Crash log from CreativeTabGC.displayAllRelevantItems

### ISSUE THREAD

**Issue by mezz** [MJRLegends/ExtraPlanets#237]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.128
Forge version: 1.12.2-14.23.1.2608

Single player (SSP) or Multiplayer (SMP)?
Both

Snippet of log:
```
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: com.google.common.collect.Ordering$IncomparableValueException: Cannot compare value: Item:(com.mjr.extraplanets.items.ItemBasicBattery@3b0da7cf),Meta:(100)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ExplicitOrdering.rank(ExplicitOrdering.java:45)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ExplicitOrdering.compare(ExplicitOrdering.java:39)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:43)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.TimSort.binarySort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.TimSort.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.Arrays.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.List.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.Collections.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at micdoodle8.mods.galacticraft.core.util.CreativeTabGC.func_78018_a(CreativeTabGC.java:50)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.create(ItemStackListFactory.java:47)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:96)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.JeiStarter.registerIngredients(JeiStarter.java:129)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:46)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Full log: https://gist.github.com/Vitali8/676abb0da286b78631fca17743e8eb57

**Comment by MJRLegends** [comment]
Fixed players just need to update :)

**Comment by MJRLegends** [comment]
I appreciate the bug report though :)

**Comment by mezz** [comment]
Thanks!
