### ISSUE TITLE
[1.12.2] Space Stations not working and giving a error

### ISSUE THREAD

**Issue by genisis1234r** [MJRLegends/ExtraPlanets#278]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Whenever i try to land on a extra planets space station on the planet selection menu, It just starts switching between text saying Taking one small step and the Galaxy map. 
### Steps to Reproduce Issue
1. [First step] Go to space and create a space station
2. [Second step] Try to land on space station

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[01:57:35] [Server thread/INFO] [STDERR]: 
**Following log added by MJRLegends**
```
[micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: java.lang.NullPointerException
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.getDefaultBiomeFor(BiomeAdaptive.java:69)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeProviderDefault.<init>(BiomeProviderDefault.java:43)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.api.prefab.world.gen.WorldProviderSpace.init(WorldProviderSpace.java:422)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.dimension.WorldProviderSpaceStation.init(WorldProviderSpaceStation.java:40)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:54)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:122)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:244)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:914)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getWorldForDimensionServer(WorldUtil.java:324)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionServer(WorldUtil.java:336)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForNameServer(WorldUtil.java:134)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:270)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_172_TickHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:730)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[01:57:35] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at java.lang.Thread.run(Unknown Source)

```
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.3.1 Minecraft 1.12.2
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]
Earths Space station does work, leading me to to suspect it it just this mods space stations that are bugged.

**Comment by MJRLegends** [comment]
Please post your full log, please use something like https://gist.github.com/

**Comment by MJRLegends** [comment]
I've can reproduce the issue and will fix for next update thanks its only 1.12.2 that affected :D

**Comment by MJRLegends** [comment]
I cant believe this wasn't picked up sooner its been broke since like 5 day on the 1.12 release, very much appreciate your bug report :D i've updated your issue report with the error it gives in the console so people can match there issue with this. 

Update will be out very soon :D

**Comment by MJRLegends** [comment]
Update is rolling out now
