### ISSUE TITLE
Error at Log (parsing)

### ISSUE THREAD

**Issue by kellixon** [MJRLegends/ExtraPlanets#381]
MC 1.12.2. Galacticraft 4.0.1.181. ExtraPlanets 0.4.5. Error at Log.
[11:38:35] [Client thread/ERROR] [FML]: Parsing error loading recipe extraplanets:nuclear_bomb
com.google.gson.JsonSyntaxException: Unknown item 'extraplanets:nuclear_bomb'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:213) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:517) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:410) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:706) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:816) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:671) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_192]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:621) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3931) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by MJRLegends** [comment]
```### ---Issue Report---

**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue

[Description of the issue]

### Steps to Reproduce Issue

1. [First step]

2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information

[Any other information that may be able to help me with the problem]

```
