### ISSUE TITLE
Launch controller not working with tier 2/3 launch pads

### ISSUE THREAD

**Issue by BluePyros** [MJRLegends/ExtraPlanets#391]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Launch controller settings not respected in regards to not breaking the launch pad at each launch or the destination setting

### Steps to Reproduce Issue
1. Place launch controller and power
2. Make sure its set to leave the launch pad
3. Build tier 2 or 3 launch pad and place rocket
4. Launch rocket and pad breaks.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [0.4.6 and 0.4.7]

**Where did this bug happen:** [Both SSP and SMP]

### Additional Information
Occured on 2 completely different modpacks, One of which is AstroBlock on the curse launcher and the other is a custom one I have been building.  May be an extension or the same as #346

**Comment by MJRLegends** [comment]
Still working on what what i want to do about this, just letting you know i havent forgot :P

**Comment by komega13** [comment]
Same issue launch pad tier 2 was broken at the launch of my tier 4 rocket + game crash . When I reconnect the rocket was up in the air and I was on the ground watching her leaving the overworld...'cry'
Concerning the crash it happens a second time when I was rebuilding the 5x5 tier 2 launch pad .
But it seems concern the cargo loader, here a sample of the log :


Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityCargoUnloader.func_73660_a(TileEntityCargoUnloader.java:58)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityCargoUnloader.func_73660_a(TileEntityCargoUnloader.java:58)

-- Block entity being ticked --
Details:
	Name: minecraft:gc cargo unloader // micdoodle8.mods.galacticraft.core.tile.TileEntityCargoUnloader
	Block type: ID #1915 (tile.cargo // micdoodle8.mods.galacticraft.core.blocks.BlockCargoLoader // galacticraftcore:cargo)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (103,71,91), Chunk: (at 7,4,11 in 6,5; contains blocks 96,0,80 to 111,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1915 (tile.cargo // micdoodle8.mods.galacticraft.core.blocks.BlockCargoLoader // galacticraftcore:cargo)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

Thanks for your works !

**Comment by MJRLegends** [comment]
Make a new issue please
