### ISSUE TITLE
Mercury boss causing issues.

### ISSUE THREAD

**Issue by OutcastZeroOne** [MJRLegends/ExtraPlanets#410]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
screen goes Black/white entering boss room of mercury dungeon

### Steps to Reproduce Issue
1. walk into boss room, one of two things happen
   a: creeper boss "spawns" but is not visable. hit it with TNT screen goes black, as in loss of video signal black.
   b: screen goes white.
**Crash log/Log (if applicable):** having issues uploading the log anywhere. but it keeps repeating this over and over
[17:27:36] [main/INFO] [FML]: Registry Block: Found a missing id from the world galaxyspace:mercuryblocks
java.lang.ClassCastException: com.mjr.extraplanets.entities.bosses.defaultBosses.EntityCreeperBossMercury cannot be cast to com.mjr.extraplanets.entities.bosses.defaultBosses.EntityCreeperBossEris
	at com.mjr.extraplanets.client.model.bosses.defaultBosses.ModelCreeperBossMercury.render(ModelCreeperBossMercury.java:107) ~[ModelCreeperBossMercury.class:?]
	at com.mjr.extraplanets.client.render.entities.bosses.defaultBosses.RenderCreeperBossMercury.doRender(RenderCreeperBossMercury.java:26) [RenderCreeperBossMercury.class:?]
	at com.mjr.extraplanets.client.render.entities.bosses.defaultBosses.RenderCreeperBossMercury.doRender(RenderCreeperBossMercury.java:12) [RenderCreeperBossMercury.class:?]

**Screenshots (if applicable):** 
![2019-03-14_17 32 27](https://user-images.githubusercontent.com/8162248/54400669-34ad2a00-4681-11e9-8667-de6032830d5b.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
ExtraPlanets-1.12.2-0.4.7
MJRLegendsLib-1.12.2-1.1.8

**Where did this bug happen:** server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Already fixed your using a old version, best to update to the latest before reporting bugs :D Thank you
