### ISSUE TITLE
Achievement issue

### ISSUE THREAD

**Issue by kmecpp** [MJRLegends/ExtraPlanets#437]
### Description of Issue
Not sure how to replicate the issue but here is the stacktrace

```
 ERROR 5: ASM: com.mjr.extraplanets.handlers.AchievementEventHandler@7cdbc5fa onCraftingRockets(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
12.06 16:54:35 [Server] WARN Failed to handle packet for /131.150.16.19:52613
12.06 16:54:35 [Server] INFO net.minecraft.util.ReportedException: Ticking player
12.06 16:54:35 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:477) ~[mw.class:?]
12.06 16:54:35 [Server] INFO at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) ~[nh.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) ~[jf.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1112) [MinecraftServer.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:921) [MinecraftServer.class:?]
12.06 16:54:35 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:738) [MinecraftServer.class:?]
12.06 16:54:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
12.06 16:54:35 [Server] INFO Caused by: java.lang.NullPointerException
12.06 16:54:36 [Multicraft] Skipped 23 lines due to rate limit (120/s)
```
### Steps to Reproduce Issue
Not sure

**Crash log/Log (if applicable):**
N/A

**Screenshots (if applicable):** 
N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.10-2.1.1

**Where did this bug happen:**
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
??

**Comment by kmecpp** [comment]
Just posted it here because ExtraPlanets was the only thing I saw in the stack trace I posted above. When I dug the whole thing out of the log I realized its probably not an ExtraPlanets issue at all. I will test it out tomorrow

**Comment by TripTripIssueTeller** [comment]
abc
