### ISSUE TITLE
Crash due to invalid input in a config option

### ISSUE THREAD

**Issue by Pipiolo13** [MJRLegends/ExtraPlanets#496]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
yes
### Description of Issue

Activating the radiation and pressurization of extra planets causes that when going to the moon, the game crashee staying in a white window

### Steps to Reproduce Issue

1. Open ExtraPlanets.cfg and change to true the options "Enable Pressure/Radiation for Galacticraft Planets & Moons"
2. In a new world, go to the Earth`s moon (whit the tier1 space suit charged, space suit of Extra Planets, and all basic space equipment -gas mask, oxigen, etc- of Galacticraft)
3. Prepare for the crash

**Crash log/Log (if applicable):** 

Description: Ticking player

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.mjr.extraplanets.handlers.MainHandlerServer.isValidSpaceSuit(MainHandlerServer.java:346)
	at com.mjr.extraplanets.handlers.MainHandlerServer.checkRadiation(MainHandlerServer.java:460)
	at com.mjr.extraplanets.handlers.MainHandlerServer.runChecks(MainHandlerServer.java:296)
	at com.mjr.extraplanets.handlers.MainHandlerServer.onEntityUpdate(MainHandlerServer.java:215)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1419_MainHandlerServer_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Screenshots (if applicable):** 
nop
**Version of Mod using:** 
Extra Planets 1.12.2-0.5.8
AsmodeusCore 1.12.2-0.0.11
GalacticraftCore 1.12.2-4.0.2.238
GalacticraftPlanets 1.12.2-4.0.2.238
GalaxySpace 1.12.2-2.0.10
MicdoodleCore1.12.2-4.0.2.238
MJRLegendsLib 1.12.2-1.1.9
More-Planets 1.12.2-2.0.22
MorePlanetsExtras 1.12.2-1.0

**Where did this bug happen:** 
Single Player
### Additional Information
If I deactivate the options, my modpack works correctly and dont crash. I clarify that activating or deactivating the pressure and radiation system is the only factor.

**Comment by MJRLegends** [comment]
Please can you post a copy of your ExtraPlanets config, you seem to have a option messed up somewhere
