### ISSUE TITLE
здраствуйте у меня проблема с вашим адоном и адоном GalaxySpace когда я открываю галактическую карту у меня экран белый а потом происходит вылет

### ISSUE THREAD

**Issue by koschk1** [MJRLegends/ExtraPlanets#497]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238 (2).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/30/19 3:18 PM
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawCircles(GuiCelestialSelection.java:2274)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1185)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:1028)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawCircles(GuiCelestialSelection.java:2274)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1185)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:1028)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection
	Mouse location: Scaled: (231, 132). Absolute: (462, 265)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['фыв'/27, l='MpServer', x=-56.50, y=4.00, z=1362.50]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-60,4,1364), Chunk: (at 4,0,4 in -4,85; contains blocks -64,0,1360 to -49,255,1375), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Level time: 405 game time, 405 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['фыв'/27, l='MpServer', x=-56.50, y=4.00, z=1362.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 423761992 bytes (404 MB) / 1020411904 bytes (973 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx1024M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.238    | GalacticraftCore-1.12.2-4.0.2.238 (2).jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.238    | Galacticraft-Planets-1.12.2-4.0.2.238 (2).jar | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.10       | AsmodeusCore-1.12.2-0.0.11.jar                | None                                     |
	| LCHIJA | mjrlegendslib       | 1.12.2-1.1.9 | MJRLegendsLib-1.12.2-1.1.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets        | 1.12.2-0.5.8 | ExtraPlanets-1.12.2-0.5.8.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | galaxyspace         | 2.0.10       | GalaxySpace-1.12.2-2.0.10.jar                 | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238 (2).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8787' Renderer: 'ATI Radeon HD 4500 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 4500 Series GL version 2.1.8787, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Space_Architect_1.7.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to fill out the issue report also use pastebin for your log
