### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by Nessark007** [MJRLegends/ExtraPlanets#513]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FutureMC (future-mc-0.1.13.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.239.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/31/19 10:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: Two space station types registered with the same home planet ID: -31
	at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.registerSpaceStation(GalacticraftRegistry.java:213)
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:15)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:331)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 747256688 bytes (712 MB) / 4731174912 bytes (4512 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                        | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCHI  | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | micdoodlecore       |                   | minecraft.jar                                 | None                                     |
	| LCHI  | futuremccore        | 0.1.12            | minecraft.jar                                 | None                                     |
	| LCHI  | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHI  | abyssalcraft        | 1.9.15            | AbyssalCraft-1.12.2-1.9.15 (1).jar            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHI  | aoa3                | 3.1.2.b           | AoA3-3.1.2.b.jar                              | None                                     |
	| LCHI  | galacticraftcore    | 4.0.2.239         | GalacticraftCore-1.12.2-4.0.2.239.jar         | None                                     |
	| LCHI  | galacticraftplanets | 4.0.2.239         | Galacticraft-Planets-1.12.2-4.0.2.239.jar     | None                                     |
	| LCHI  | asmodeuscore        | 0.0.12            | AsmodeusCore-1.12.2-0.0.12.jar                | None                                     |
	| LCHI  | atum                | 2.0.16            | Atum-1.12.2-2.0.16.jar                        | None                                     |
	| LCHI  | casinocraft         | v06               | CasinoCraft_1.12.2_v06.jar                    | None                                     |
	| LCHI  | chaotica            | 4.8.5             | Chaotica_v4.8.51fixed[1.12.2].jar             | None                                     |
	| LCHI  | ctm                 | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
	| LCHI  | customnpcs          | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar               | None                                     |
	| LCHI  | erebus              | 1.0.31            | Erebus-1.0.31.jar                             | None                                     |
	| LCHI  | mjrlegendslib       | 1.12.2-1.1.9      | MJRLegendsLib-1.12.2-1.1.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | zollerngalaxy       | 2.0.8             | ZollernGalaxy-1.12.2-v2.0.8.jar               | None                                     |
	| LCHE  | extraplanets        | 1.12.2-0.6.0      | ExtraPlanets-1.12.2-0.6.0.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | minecraftfuture     | 0.1.13            | future-mc-0.1.13.jar                          | None                                     |
	| LCH   | galaxyspace         | 2.0.11            | GalaxySpace-1.12.2-2.0.11.jar                 | None                                     |
	| LCH   | incontrol           | 3.9.16            | incontrol-1.12-3.9.16.jar                     | None                                     |
	| LCH   | jeid                | 1.0.3-48          | JustEnoughIDs-1.0.3-48.jar                    | None                                     |
	| LCH   | moreplanets         | 2.0.22            | More-Planets-1.12.2-2.0.22-GC238.jar          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | moreplayermodels    | 1.12.2            | MorePlayerModels_1.12.2-(05Dec19).jar         | None                                     |
	| LCH   | neat                | 1.4-17            | Neat+1.4-17.jar                               | None                                     |
	| LCH   | patchouli           | 1.0-20            | Patchouli-1.0-20.jar                          | None                                     |
	| LCH   | supertnt            | 1.0.1             | SuperTNT-1.12.2-1.0.1.jar                     | None                                     |
	| LCH   | theaurorian         | 1.12.2-Beta       | theaurorian-1.12.2-beta-dec2919.jar           | None                                     |
	| LCH   | thecrystallia       | 1.0.8             | TheCrystallia+1.0.9+[1.12.2].jar              | None                                     |
	| LCH   | twilightforest      | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCH   | xaerominimap        | 1.19.5            | Xaeros_Minimap_1.19.5_Forge_1.12.jar          | None                                     |
	| LCH   | xaeroworldmap       | 1.5.2             | XaerosWorldMap_1.5.2_Forge_1.12.jar           | None                                     |
	| LCH   | thebetweenlands     | 3.5.4             | TheBetweenlands-3.5.4-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.239.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7263' Renderer: 'Intel(R) UHD Graphics 630'

**Comment by MJRLegends** [comment]
You didnt follow https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/ since you got other addons
