### ISSUE TITLE
Galacticraft crushes..

### ISSUE THREAD

**Issue by Torsons** [MJRLegends/ExtraPlanets#560]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  FutureMC (future-mc-1.12.2-0.2.3.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/10/20 11:54 PM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
	at com.mjr.extraplanets.tileEntities.machines.TileEntityAdvancedRefinery.<init>(TileEntityAdvancedRefinery.java:46)
	at com.mjr.extraplanets.blocks.machines.AdvancedRefinery.createTileEntity(AdvancedRefinery.java:94)
	at micdoodle8.mods.galacticraft.core.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:84)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$463/1152622941.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$466/1251542787.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mjr.extraplanets.tileEntities.machines.TileEntityAdvancedRefinery.<init>(TileEntityAdvancedRefinery.java:46)
	at com.mjr.extraplanets.blocks.machines.AdvancedRefinery.createTileEntity(AdvancedRefinery.java:94)
	at micdoodle8.mods.galacticraft.core.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:84)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$463/1152622941.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$466/1251542787.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400432816 bytes (381 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version        | Source                                         | Signature                                |
	|:----- |:------------------- |:-------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2         | minecraft.jar                                  | None                                     |
	| LCH   | mcp                 | 9.42           | minecraft.jar                                  | None                                     |
	| LCH   | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854   | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                | minecraft.jar                                  | None                                     |
	| LCH   | ic2                 | 2.8.186-ex112  | Industrial-Craft-2-Mod-Experimental-1.12.2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | jei                 | 4.15.0.291     | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCH   | forestry            | 5.8.2.408      | Forestry-Mod-1.12.2.jar                        | None                                     |
	| LCH   | binniecore          | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | binniedesign        | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | genetics            | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | botany              | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | extrabees           | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | extratrees          | 2.5.1.203      | binnie-mods-1.12.2-2.5.1.203.jar               | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.280      | GalacticraftCore-1.12.2-4.0.2.280.jar          | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280      | Galacticraft-Planets-1.12.2-4.0.2.280.jar      | None                                     |
	| LCH   | mjrlegendslib       | 1.12.2-1.1.9   | MJRLegendsLib-1.12.2-1.1.9.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | extraplanets        | 1.12.2-0.3.8   | ExtraPlanets-1.12.2-0.3.8.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | forgelin            | 1.8.4          | Forgelin-1.8.4.jar                             | None                                     |
	| LCH   | futuremc            | 0.2.3          | future-mc-1.12.2-0.2.3.2.jar                   | None                                     |
	| LCH   | gravisuite          | 3.1.1          | gravitationsuite-3.1.1.jar                     | None                                     |
	| LCH   | llor                | 1.1.6-mc1.12.2 | LLOverlayReloaded-1.1.6-mc1.12.2.jar           | None                                     |
	| LCH   | moreplanets         | 2.0.24         | More-Planets-1.12.2-2.0.24-GC251.jar           | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | wanionlib           | 1.12.2-2.4     | wanionlib-1.12.2-2.4.jar                       | None                                     |
	| LCH   | unidict             | 1.12.2-2.9.6   | unidict-1.12.2-2.9.6.jar                       | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
FutureMC (future-mc-1.12.2-0.2.3.2.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.20' Renderer: 'GeForce GT 1030/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.20, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

**Comment by MJRLegends** [comment]
Please next time use issue template as you did everything it says not to do like post the whole crash log here.

Normally i just delete the issue report if you dont use the issue template. 

But either way you dont actually need to just update all your mods and you will be fine

**Comment by MJRLegends** [comment]
You using years old ExtraPlanets version
