### ISSUE TITLE
[1.8] Crash while landing on moon(actually i don't know whether its the add-on's issue or galactic raft issue)

### ISSUE THREAD

**Issue by CKTheUltimate** [MJRLegends/ExtraPlanets#62]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39-BETA.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/24/17 6:04 PM
Description: Unexpected error

java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.dimension.WorldProviderMoon cannot be cast to com.mjr.extraplanets.world.EPWorldProviderSpace
	at com.mjr.extraplanets.client.handlers.MainClientHandler.onRenderTick(MainClientHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_132_MainClientHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mjr.extraplanets.client.handlers.MainClientHandler.onRenderTick(MainClientHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_132_MainClientHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['CKTheUltimate'/189, l='MpServer', x=-316.50, y=900.00, z=-647.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 8.00,64.00,8.00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12672 game time, 12672 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['CKTheUltimate'/189, l='MpServer', x=-316.50, y=900.00, z=-647.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.12.2
	CPU: 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 314993584 bytes (300 MB) / 951046144 bytes (906 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H6 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.0.39-BETA.jar) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.0.39-BETA.jar) 
	UCHIJAAAA	ExtraPlanets{0.3-Alpha-Build} [Extra Planets] (ExtraPlanets-0.3-Alpha-Build.jar) 
	UCHIJAAAA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 455 OpenGL Engine GL version 2.1 ATI-1.48.16, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H6
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-1.48.16
	OpenGlRenderer: AMD Radeon Pro 455 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by MJRLegends** [comment]
Ok will release a new build soon with a fix, btw for future please use the template provided and post logs in a pastebin.com

**Comment by MJRLegends** [comment]
0.3.5-Alpha-Build is out fixing this. Any more bugs please let me know
