### ISSUE TITLE
crash on trying render item

### ISSUE THREAD

**Issue by SachaTending** [MJRLegends/ExtraPlanets#725]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
[Description of the issue]

### Steps to Reproduce Issue(Required)
1. im launched minecraft and joined to creative flat world
2. opened inventory and clicked to next items list button

**Crash log/Log (if applicable):**  in end

**Screenshots (if applicable):** 

**Mod List (Required):** 
in crash log(because LoliAsm)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 1.12.2 - 0.7.4

**Where did this bug happen(Required):** single player

### Additional Information
[Any other information that may be able to help me with the problem]

crash log: java.lang.reflect.InvocationTargetException: null
>> 	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[?:?]
>> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>> 	at net.optifine.reflect.Reflector.call(Reflector.java:808) [Reflector.class:?]
>> 	at net.minecraft.client.renderer.RenderItem.renderItemModelIntoGUI(RenderItem.java:508) [bzw.class:?]
>> 	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:559) [bzw.class:?]
>> 	at codechicken.lib.render.item.CCRenderItem.renderItemAndEffectIntoGUI(CCRenderItem.java:356) [CCRenderItem.class:?]
>> 	at codechicken.lib.render.item.CCRenderItem.renderItemAndEffectIntoGUI(CCRenderItem.java:323) [CCRenderItem.class:?]
>> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawTab(GuiContainerCreative.java:922) [bmp.class:?]
>> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:758) [bmp.class:?]
>> 	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75) [bmg.class:?]
>> 	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:51) [bmr.class:?]
>> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:643) [bmp.class:?]
>> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
>> 	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[?:?]
>> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) [Reflector.class:?]
>> 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1462) [buq.class:?]
>> 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
>> 	at net.minecraft.client.Minecraft.run(Minecraft.java:3614) [bib.class:?]
>> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
>> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
>> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
>> Caused by: java.lang.IllegalAccessError: tried to access method javax.vecmath.Matrix3d.compute_svd([D[D[D)V from class javax.vecmath.Matrix4f
>> 	at javax.vecmath.Matrix4f.getScaleRotate(Matrix4f.java:3239) ~[vecmath-1.5.2.jar:1.5.2]
>> 	at javax.vecmath.Matrix4f.setRotation(Matrix4f.java:3049) ~[vecmath-1.5.2.jar:1.5.2]
>> 	at com.mjr.extraplanets.client.model.rockets.ItemModelRocketT4.getTransformForPerspective(ItemModelRocketT4.java:40) ~[ItemModelRocketT4.class:?]
>> 	at com.mjr.mjrlegendslib.client.model.ModelTransformWrapper.handlePerspective(ModelTransformWrapper.java:70) ~[ModelTransformWrapper.class:?]
>> 	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:427) ~[ForgeHooksClient.class:?]
>> 	... 28 more

**Comment by SachaTending** [comment]
full crash log
[crash-2022-08-17_07.21.17-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/9357492/crash-2022-08-17_07.21.17-client.txt)

**Comment by MJRLegends** [comment]
Please report to LoliASM as i thinking its there changes causing issues, and it will be hard for me to debug from my end
