### ISSUE TITLE
mod not working (Was MISSING MJRLegendsLib)

### ISSUE THREAD

**Issue by samet9999** [MJRLegends/ExtraPlanets#785]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Description of Issue(Required)
[Description of the issue]

### Steps to Reproduce Issue(Required)
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] 
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![Ekran görüntüsü 2024-06-03 183325](https://github.com/MJRLegends/ExtraPlanets/assets/156913291/d9f65c20-e646-4433-8322-e36aa19e76c6)

**Mod List (Required):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]

**Where did this bug happen(Required):** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]
[18:33:44] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:33:44] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:33:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:33:45] [main/INFO]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[18:33:45] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\İbrahim BALCI\AppData\Roaming\.minecraft\runtime\jre-legacy\wındows\jre-legacy
[18:33:45] [main/INFO]: Searching C:\Users\İbrahim BALCI\AppData\Roaming\.minecraft\versions\galaaaa\mods for mods
[18:33:45] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:33:45] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[18:33:45] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in tlskincape1.12.2-1.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:33:45] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:33:45] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:33:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:33:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:33:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:33:48] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:33:48] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:33:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:33:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:33:48] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[18:33:49] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[18:33:49] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[18:33:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:33:49] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Parsing hooks container gloomyfolken.hooklib.minecraft.SecondaryTransformerHook
[18:33:49] [main/INFO]: [HOOKLIB]  Obfuscated: true
[18:33:49] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Parsing hooks container org.tlauncher.skin.cape.asm.TLSkinCapeHooks
[18:33:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:33:49] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraftforge.fml.common.Loader
[18:33:49] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraftforge.fml.common.Loader#injectData([Ljava/lang/Object;)
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Methods dictionary loaded in 7 ms
[18:33:50] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:33:50] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:33:50] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraft.client.entity.AbstractClientPlayer
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraft.client.entity.AbstractClientPlayer#getLocationSkin()Lnet/minecraft/util/ResourceLocation;
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraft.client.entity.AbstractClientPlayer#getLocationCape()Lnet/minecraft/util/ResourceLocation;
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraft.client.entity.AbstractClientPlayer#getSkinType()
[18:33:50] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraft.entity.player.EntityPlayer
[18:33:51] [main/INFO]: [gloomyfolken.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraft.entity.player.EntityPlayer#isWearing(Lnet/minecraft/entity/player/EnumPlayerModelParts;)
[18:33:52] [Client thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[18:33:52] [Client thread/INFO]: Setting user: samet222
[18:33:59] [Client thread/WARN]: Skipping bad option: lastServer:
[18:33:59] [Client thread/INFO]: LWJGL Version: 2.9.4
[18:34:02] [Client thread/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 442445496 bytes (421 MB) / 939524096 bytes (896 MB) up to 6308233216 bytes (6016 MB)
	JVM Flags: 7 total; -Xmx5992M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.10.24.02.230811' Renderer: 'AMD Radeon(TM) Graphics'
[18:34:03] [Client thread/INFO]: MinecraftForge v14.23.5.2859 Initialized
[18:34:03] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[18:34:03] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[18:34:03] [Client thread/INFO]: Replaced 1227 ore ingredients
[18:34:05] [Client thread/INFO]: Searching C:\Users\İbrahim BALCI\AppData\Roaming\.minecraft\versions\galaaaa\mods for mods
[18:34:06] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 198184000 nanos
[18:34:09] [Client thread/INFO]: Forge Mod Loader has identified 10 mods to load
[18:34:09] [Client thread/FATAL]: net.minecraftforge.fml.common.MissingModsException: Mod extraplanets (Extra Planets) requires [mjrlegendslib@[1.12.2-1.2.1,)]
[18:34:09] [Client thread/ERROR]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod extraplanets (Extra Planets) requires [mjrlegendslib@[1.12.2-1.2.1,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:34:09] [Client thread/WARN]: EventBus 0 shutting down - future events will not be posted.
[18:34:09] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Extra Planets, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:SpaceAmbient, FMLFileResourcePack:TLSkinCape
[18:34:09] [Client thread/WARN]: There were errors previously. Not beginning mod initialization phase
[18:34:13] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:34:14] [Thread-5/INFO]: Initializing LWJGL OpenAL
[18:34:14] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:34:16] [Thread-5/INFO]: OpenAL initialized.
[18:34:16] [Sound Library Loader/INFO]: Sound engine started
[18:34:16] [Client thread/INFO]: Narrator library for x64 successfully loaded

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.MissingModsException: Mod extraplanets (Extra Planets) requires [mjrlegendslib@[1.12.2-1.2.1,)] very simple.
