### ISSUE TITLE
Random crash when clicking on Space Stations

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#792]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Description of Issue(Required)
[Sometimes when I click the Space Station, the game will crash do to an error with updating the screen events. : PS I don't want to create a Pastebin account, I just want to post this crash report.]

### Steps to Reproduce Issue(Required)
1. [Launch rocket]
2. [Click on Space Station]

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/20/24 2:18 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73864_a(GuiCelestialSelection.java:938)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_146269_k(GuiCelestialSelection.java:630)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73864_a(GuiCelestialSelection.java:938)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_146269_k(GuiCelestialSelection.java:630)

-- Affected screen --
Details:
	Screen name: com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['SR8TLine'/6, l='MpServer', x=-641.31, y=73.12, z=-744.03]]
	Chunk stats: MultiplayerChunkCache: 1079, 1079
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 72993 game time, 2677 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [GCEntityClientPlayerMP['SR8TLine'/6, l='MpServer', x=-641.31, y=73.12, z=-744.03], EntityCelestialFake['entity.CelestialScreen.name'/68213, l='MpServer', x=-641.31, y=72.00, z=-744.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 410216968 bytes (391 MB) / 2314207232 bytes (2207 MB) up to 28872015872 bytes (27534 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx30976m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 28
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-1.7-3.0.12.504.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-1.7-3.0.12.504.jar) 
	UCHIJAAAA	ExtraPlanets{1.7.10-2.1.4} [Extra Planets] (ExtraPlanets-1.7.10-2.1.4.jar) 
	UCHIJAAAA	weather2{v2.3.19} [Localized Weather & Storms] (weather2-1.7.10-2.3.20.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 560.94' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [GalactiCircle.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Screenshots (None):** 

**Mod List (ExtraPlanets Galacticraft Legacy Minecraft 1.7.10):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [ExtraPlanets-1.7.10-2.1.4]

**Where did this bug happen(Required):** [Single Player]

### Additional Information
[The crash might be a problem with the custom celestial screen map.]

**Comment by ghost** [comment]
I think it would be more fair if users didn't have to create a third party account.
