### ISSUE TITLE
(1.7.10) 1.6.4 crashes server on startup due to calling client sided rendering

### ISSUE THREAD

**Issue by McyD** [MJRLegends/ExtraPlanets#82]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/21/17 7:43 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Serious error calling getRenderType() on block ExtraPlanets:tile.advancedLaunchPadFull
	at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:85)
	at com.rwtema.extrautils.ExtraUtils.postInit(ExtraUtils.java:1326)
	at com.rwtema.extrautils.ExtraUtilsMod.postInit(ExtraUtilsMod.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.mjr.extraplanets.proxy.ClientProxy.getBlockRender(Lnet/minecraft/block/Block;)I
	at com.mjr.extraplanets.blocks.BlockCustomLandingPadFull.func_149645_b(BlockCustomLandingPadFull.java:96)
	at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:78)
	... 33 more

**Comment by MJRLegends** [comment]
Check out open issues before posting as its already posted!

**Comment by McyD** [comment]
was posted as the other was reported before the last release.

**Comment by MJRLegends** [comment]
Please read comments on open issue about this
